[package]
name = "switchboard-solana"
version = "0.0.1"
edition = "2021"
description = "A Rust library to interact with Switchboard accounts."
readme = "README.md"
keywords = ["switchboard", "oracle", "solana"]
homepage = "https://docs.switchboard.xyz"
repository = "https://github.com/switchboard-xyz/sgx-sdk/tree/main/rust/solana"
license = "MIT"
documentation = "https://docs.switchboard.xyz"

[lib]
crate-type = ["cdylib", "lib"]
name = "switchboard_solana"
doctest = false

[features]
default = ["cpi"]
no-entrypoint = []
cpi = ["no-entrypoint"]
client = [
    "switchboard-common/sgx",
    "dep:anchor-client",
    "dep:bincode",
    "dep:sgx-quote",
    "dep:cron",
    "dep:chrono"
]

[dependencies]
switchboard-common = { version = "0.0.1" }
rust_decimal = "1"
bytemuck = "1.13.1"
superslice = "1"
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
solana-program = ">= 1.13.5, < 1.15"
# These may not be needed, anchor27 keeps complaining
winnow = "=0.4.1"
toml_edit = "=0.19.8"
toml_datetime = "=0.6.1"
anchor-client = { version = "0.27.0", optional = true }
bincode = { version = "1.3.3", optional = true }
sgx-quote = { version = "0.1.0", optional = true }
cron = { version = "0.12.0", optional = true }
chrono = { version = "0.4.25", optional = true }
