[package]
name = "switchboard-solana"
version = "0.8.12"
edition = "2021"
description = "A Rust library to interact with Switchboard accounts."
readme = "README.md"
keywords = ["switchboard", "oracle", "solana"]
homepage = "https://docs.switchboard.xyz"
repository = "https://github.com/switchboard-xyz/sbv2-solana/tree/main/rust/switchboard-solana"
license = "MIT"
documentation = "https://docs.switchboard.xyz"

[lib]
crate-type = ["cdylib", "lib"]
name = "switchboard_solana"
doctest = false

[features]
default = ["cpi"]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-spl = "0.27.0"
solana-program = "=1.14.16"
solana-address-lookup-table-program = "=1.14.16"
rust_decimal = "^1"
bytemuck = "^1"
superslice = "1"

[target.'cfg(target_os = "solana")'.dependencies]
switchboard-common = { version = "0.8.5" }
anchor-lang = { version = "0.27.0" }

[target.'cfg(not(target_os = "solana"))'.dependencies]
switchboard-common = { version = "0.8.5", features = ["client"] }
anchor-client = { version = "0.27.0" }
solana-client = "=1.14.16"
bincode = { version = "^1" }
sgx-quote = { version = "0.1.0" }
cron = { version = "0.12.0" }
chrono = { version = "0.4.25" }
hex = "0.4.3"
tokio = "1.29.1"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "doc_cfg"]
